### ISSUE TITLE
OBIS sequence data

### ISSUE THREAD

**Issue by humbleflowers** [iobis/sequence-search#9]
Hello @pieterprovoost 

Is there a way i can download underlying nucleotide fasta database from OBIS to do analysis?

Thank you.

**Comment by pieterprovoost** [comment]
@humbleflowers This can be done using the robis R package, but it can be fairly slow to get the entire database. Let me know if you would like to have a full export.

This is an example for just the most recent data (2022 onwards):

```r
library(robis)

occ <- occurrence(hasextensions = "DNADerivedData", extensions = "DNADerivedData", startdate = "2022-01-01")
dna <- unnest_extension(occ, "DNADerivedData", fields = c("scientificName", "decimalLongitude", "decimalLatitude", "eventDate", "datasetName", "materialSampleID"))
```

**Comment by humbleflowers** [comment]
Hello @pieterprovoost , Thanks for the reply.
I would like to have a full export. 
Do you know how big is the FASTA file?

**Comment by humbleflowers** [comment]
@pieterprovoost , i got the files i needed through R commands. Thank you.
